# config.yml

# chat messages
messages:
  unknown_command: "§cUnknown command. Type /help for help."
  no_permission: "§cYou do not have permission to use this command."

# Default spawn locations per world
world_spawns:
  world:
    x: 0.5
    y: 64
    z: 0.5
  world_nether:
    x: 0.5
    y: 64
    z: 0.5
  world_the_end:
    x: 100
    y: 128
    z: 100

# Server Info Display Config
tablist:
  header: |
    §a§lHOT §2§lBLOX
  footer: |
    §9Discord: &7discord.jxsh.space 

scoreboard:
  title: "§a§lHOT §2§lBLOX"
  lines:
    - "§7------------------"
    - "§ePlayer: §f%player%"
    - "§eOnline: §f%online_players% / %max_players%"
    - "§7"
    - "§bdev.jxsh.space"
    - "§7------------------"

# Permission nodes for custom suffixes/prefixes
permission_nodes:
  - "prefix.&a[Admin]"
  - "suffix.&b[Member]"
