# BloxHub Config - PreRelease
# BloxHub is created by The_Blue_Goose and Jxsh
# This plugin was made for the HotBlox Server

# chat messages
chat:
  format: "%prefix%§r%player% §8» §r§f%message%"
  unknown_command: "§cUnknown command. Type /help for help."
  no_permission: "§cYou do not have permission to use this command."
  join_message: "§a%player% just joined!"
  first_join_message: "§bWelcome %player% to BloxHub for the first time!"
  death_message: "§c%player% died."

# Command Config
teleport:
  timeout-seconds: 60   #time to accept tpa request (seconds)

# Server Info Display Config (animates between 1 and 2)
tablist:
  # If animation is false, it will use the config at "1" only
  # If animation is on. it will cycle between 1 and 2
  Animation: true
  1:
    header: |
      §7Welcome to §a§lHot§2§lBlox
    footer: |
      §2
      §9Discord: §7discord.jxsh.space
  2:
    header: |
      §7Welcome to §2§lHot§a§lBlox
    footer: |
      §2
      §9Discord: §7discord.jxsh.space

scoreboard:
  title: "§a§lHOT §2§lBLOX"
  lines:
    - "§7§m------------------"
    - "§ePlayer: §f%player_name%"
    - "§eOnline: §f%server_online% / %server_max_players%"
    - "§7"
    - "§eRank: §b%luckperms_primary_group_name%"
    - "§9"
    - "§bdev.jxsh.space"
    - "§7§m------------------"

# Permission nodes for custom suffixes/prefixes
permission_nodes:
  - "prefix.&a[Admin]"
  - "suffix.&b[Member]"