# BloxHub Config - PreRelease
# BloxHub is created by The_Blue_Goose and Jxsh
# This plugin was made for the HotBlox Server

# chat messages
messages:
  unknown_command: "§cUnknown command. Type /help for help."
  no_permission: "§cYou do not have permission to use this command."

# Default spawn locations per world
world_spawns:
  world:
    x: 0.5
    y: 64
    z: 0.5
  world_nether:
    x: 0.5
    y: 64
    z: 0.5
  world_the_end:
    x: 100
    y: 128
    z: 100

# Server Info Display Config
tablist:
  header: |
    §7Welcome to §a§lHot§2§lBlox
  footer: |
    §2
    §9Discord: §7discord.jxsh.space

scoreboard:
  title: "§a§lHOT §2§lBLOX"
  lines:
    - "§7§m------------------"
    - "§ePlayer: §f%player_name%"
    - "§eOnline: §f%server_online% / %server_max_players%"
    - "§7"
    - "§eRank: §b%luckperms_primary_group_name%"
    - "§9"
    - "§bdev.jxsh.space"
    - "§7§m------------------"

# Permission nodes for custom suffixes/prefixes
permission_nodes:
  - "prefix.&a[Admin]"
  - "suffix.&b[Member]"
