name: BloxHub
version: '0.1.0-TestVer'
main: BlueGoose.bloxHub.BloxHub
authors: [The_Blue_Goose, Jxsh]
api-version: '1.18'

commands:
  setspawn:
    description: Sets the world spawn point to your location or provided coordinates.
    usage: /<command> [x] [y] [z]
    permission: blox.setspawn
    aliases: [sets, setsp]
  spawn:
    description: Teleports you to the world spawn point.
    usage: /<command>
    permission: blox.spawn
    aliases: [s, hub, lobby]

  gm:
    description: Toggles or sets your gamemode.
    usage: /<command> [mode] [player]
    permission: blox.gamemode
  gmc:
    description: Sets gamemode to creative.
    usage: /<command> [player]
    permission: blox.gamemode
  gms:
    description: Sets gamemode to survival.
    usage: /<command> [player]
    permission: blox.gamemode
  gma:
    description: Sets gamemode to adventure.
    usage: /<command> [player]
    permission: blox.gamemode
  gmsp:
    description: Sets gamemode to spectator.
    usage: /<command> [player]
    permission: blox.gamemode

  scoreboard:
    description: Toggle your scoreboard visibility.
    usage: /<command>
    permission: blox.scoreboard
    aliases: [ sb ]

  heal:
    description: Fully heals a player (health + hunger + 3/10 saturation).
    usage: /<command> [player]
    permission: blox.heal
  feed:
    description: Fills hunger and saturation.
    usage: /<command> [player]
    permission: blox.feed

  fly:
    description: Toggles flight mode.
    usage: /<command> [player]
    permission: blox.fly
  god:
    description: Toggles god mode (no damage).
    usage: /<command> [player]
    permission: blox.god

permissions:
  blox.setspawn:
    default: op
  blox.spawn:
    default: true
  blox.gamemode:
    default: op
  blox.scoreboard:
    default: true
  blox.heal:
    default: op
  blox.feed:
    default: op
  blox.fly:
    default: op
  blox.god:
    default: op
  blox.bypass.blockedcommands:
    description: Allows use of blocked server commands like /pl and /version
    default: op