name: BloxHub
version: '1.0-SNAPSHOT'
main: BlueGoose.bloxHub.BloxHub
authors: [The_Blue_Goose, Jxsh]
api-version: '1.18'

commands:
  setspawn:
    description: Sets the world spawn point to your location or provided coordinates.
    usage: /<command> [x] [y] [z]
    permission: bloxhub.setspawn
    aliases: [sets, setsp]
  spawn:
    description: Teleports you to the world spawn point.
    usage: /<command>
    permission: bloxhub.spawn
    aliases: [s]
  gm:
    description: Toggles or sets your gamemode.
    usage: /<command> [mode]
    permission: bloxhub.gamemode
  gmc:
    description: Sets gamemode to creative.
    usage: /<command>
    permission: bloxhub.gamemode
  gms:
    description: Sets gamemode to survival.
    usage: /<command>
    permission: bloxhub.gamemode
  gma:
    description: Sets gamemode to adventure.
    usage: /<command>
    permission: bloxhub.gamemode
  gmsp:
    description: Sets gamemode to spectator.
    usage: /<command>
    permission: bloxhub.gamemode
  scoreboard:
    description: Toggle your scoreboard visibility.
    usage: /<command>
    permission: bloxhub.scoreboard
    aliases: [ sb ]

permissions:
  bloxhub.setspawn:
    default: op
  bloxhub.spawn:
    default: true
  bloxhub.gamemode:
    default: op
  bloxhub.scoreboard:
    default: true